version: 2

sources:
  - name: snowflake_sample_data
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    description: "Snowflake sample TPCH Dataset"
    tables:
      - name: CUSTOMER
        description: "Customer Data"

      - name: REGION
        description: "REGION Data"

      - name: LINEITEM
        description: "This is fact data"
